#-------------------------------
# General Site Settings

email: osullivancj@gmail.com


menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section


seo:
  description: 'Front End Developer for hire.'


#-------------------------------
# About Section

blurb: >
  My name is Colin, and I am a front-end developer based in Ohio. I am passionate about solving problems while exploring new ways to build the web. I am currently available for a fulltime position or freelance work.


skills:

- {name: JavaScript, value: '8'}
- {name: CSS, value: '8'}
- {name: ReactJS, value: '7'}
- {name: SQL, value: '6'}
- {name: Design, value: '5'}
- {name: Backend, value: '5'}
